<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType> <!-- Changed from Exe to WinExe for Windows Application -->
        <TargetFramework>net6.0-windows</TargetFramework> <!-- Added -windows for WinForms -->
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms> <!-- Added for WinForms support -->
        <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Drawing.Common" Version="8.0.2" />
    </ItemGroup>

</Project>
