<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType> <!-- Reverted to Exe -->
        <TargetFramework>net6.0</TargetFramework> <!-- Reverted to net6.0 -->
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- Removed <UseWindowsForms>true</UseWindowsForms> -->
        <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Drawing.Common" Version="8.0.2" />
      <PackageReference Include="Spectre.Console" Version="0.48.0" />
    </ItemGroup>

</Project>
